import = [
  "~/.config/alacritty/rose-pine.toml"
]

[env]
TERM = "xterm-256color"

[window]
  decorations = "buttonless"
  opacity = 1 
  dynamic_padding = true 

[window.padding]
   x = 2 
   y = 2 

[font]
  size = 14.5 
  normal = {family="MesloLGL Nerd Font Mono", style="Regular"}
  bold = {family="MesloLGL Nerd Font Mono"}
  italic =  {family="MesloLGL Nerd Font Mono"}
  bold_italic = {family="MesloLGL Nerd Font mono"}
  offset.x = 0 
  offset.y = -1

[scrolling]
    history = 100000

[mouse]
  hide_when_typing = true
