import = [
  #"~/.config/alacritty/catppuccin-mocha.toml"
  #"~/.config/alacritty/solarized.toml"
  "~/.config/alacritty/rose-pine.toml"
]

[env]
  TERM = "xterm-256color"

[window]
  decorations = "buttonless"
  opacity = 1 

  dynamic_padding = true 

[window.padding]
   x = 2 
   y = 2 

[font]
  size = 14.5 
  normal = {family="FiraCode Nerd Font", style="Regular"}
  bold = {family="FiraCode Nerd Font"}
  italic =  {family="FiraCode Nerd Font"}
  bold_italic = {family="FiraCode Nerd Font"}
  offset.x = 0 
  offset.y = 2 

[scrolling]
    history = 100000

[mouse]

  hide_when_typing = true
