# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory $git_branch $git_status
$python$character """

# Inserts a blank line between shell prompts
add_newline = false 
palette = "rose-pine"

[character] # The name of the module we are configuring is ''
success_symbol = "[>_](bold iris)" # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = "[>_](bold love)"

[directory]
truncation_length = 0 
truncate_to_repo = false 
style = "gold"
format = "[$path]($style)"


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
# Don't trigger for files with the py extension
detect_extensions = []
style = "rose"
format = "[$virtualenv]($style) "

[conda]
style = "love"
format = '([$environment]($style) )'
ignore_base = false

[git_branch]
format = " [$branch](bold foam)"

[git_status]
style = "love"
format = '([$all_status$ahead_behind]($style) )'

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
