# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = "[ric@local](teal) in $directory $character"
right_format = "$conda$git_branch $git_status"

# Inserts a blank line between shell prompts
add_newline = false 
palette = "catppuccin_mocha"

[character] # The name of the module we are configuring is 'character'
success_symbol = '[❯](green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = "[❯](red)"

[directory]
truncation_length = 0 
truncate_to_repo = false 
style = "rosewater"
format = "[$path]($style)"


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
# Don't trigger for files with the py extension
detect_extensions = []

[conda]
format = 'in [$environment](dimmed green) '
ignore_base = false

[git_branch]
format = "on [$branch](mauve)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
