return {
	--		"stevearc/conform.nvim",
	--		event = { "BufReadPre", "BufNewFile" },
	--		config = function()
	--			local conform = require("conform")
	--			conform.setup({
	--				formatters_by_ft = {
	--					lua = { "stylua" },
	--					python = { "isort", "ruff" },
	--				},
	--				format_on_save = {
	--					lsp_fallback = true,
	--					async = false,
	--					timeout_ms = 5000,
	--				},
	--			})
	--			vim.keymap.set({ "n", "v" }, "<leader>gf", function()
	--				conform.format({
	--					lsp_fallback = false,
	--					async = true,
	--					timeout_ms = 5000,
	--				})
	--			end)
	--		end,
}
